### ISSUE TITLE
Improve the overall quality and outlook of the site http://fennica-fennica.rahtiapp.fi/

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#11]

**Comment by pitkant** [comment]
Please also note that the project this site is currently on (Fennica test project) and the URL structure is probably not in its final form. We can make all changes to this iteration and then move it to a more permanent project with better thought out naming scheme.

How the URL is constructed: If I remember correctly, the first "fennica" in fennica-fennica is namespace and the second "fennica" is project name.
