### ISSUE TITLE
Migrate comhis package code into fennica package

### ISSUE THREAD

**Issue by pitkant** [fennicahub/fennica#13]
Having to rely on an external repository has become cumbersome and it would be good to move code that fennica package depends into fennica package. This would not change the attributions in fennica package as code contributions in comhis package are from @antagomir (https://github.com/COMHIS/comhis/graphs/contributors)

- [ ] Move at least comhis functions that fennica package is dependent on into fennica
- [ ] OPTIONALLY, if the functions are very interlinked with each other, move all functions from comhis into fennica package
- [ ] Update necessary GitHub Actions, Fennica DESCRIPTION file etc. to reflect the made changes

 @ake123 can coordinate this task and delegate work as you see fit

**Comment by antagomir** [comment]
Sounds good!

**Comment by antagomir** [comment]
Ready?

**Comment by ake123** [comment]
It's not ready yet

**Comment by antagomir** [comment]
Please close the issues when they are done.
