### ISSUE TITLE
DHL-FI website

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#25]

**Comment by JuliaMatveeva217** [comment]
Ask IT department how to create a website for DHL-FI project. Webpage has to be easy to update for a person with limited technical knowledge (Jeba)
Julia foresees the content of the webpage with Kati Launis

**Comment by JuliaMatveeva217** [comment]
has to be done before autumn 2023

**Comment by antagomir** [comment]
the right place is IT helpdesk

**Comment by JuliaMatveeva217** [comment]
done and working on the context with Kati
