### ISSUE TITLE
Remove obsolete fields from website output

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#49]
Remove unneeded fields.

Exclude for now - we can consider these later:
502a - dissertation_note
502c - name of granting institution
650a - topical term (geography)
502d - year degree granted

Are these important? If yes, then let's include. If not, remove. If unclear, check.
852a holder location  
510a - name of source
785t - succeding entry
720a - name uncontrolled

**Comment by JuliaMatveeva217** [comment]
In my opinion these are not important for now. I will comment them out.

**Comment by JuliaMatveeva217** [comment]
Osma said there is no holder info in Fennica. Where did you get it from? I could not find in the files.

**Comment by antagomir** [comment]
It could be that it has been originally separated from author or publisher field (role). We do not need this, doesn't have to be in the book.

**Comment by JuliaMatveeva217** [comment]
ok
I will comment this out as well

**Comment by antagomir** [comment]
If the holder field refers to the signum information then it probably should be kept. I confused it with publisher subtypes.
