### ISSUE TITLE
sessionInfo()

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#56]
The sessionInfo() is now shown on the [landing page](http://fennica-fennica.rahtiapp.fi/) of the book. 

I suggest to move it into a separate section in the end. The section can be without section number, and title for instance "Technical information". That section can also include pointers to the documentation on how to reproduce the gitbook and possibly other relevant technical information regarding the work.

**Comment by ElliotvGP** [comment]
it has been added in the "appendices"section of the book
