### ISSUE TITLE
TOC disappears when scrolling

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#57]
The Table of Contents in [Rahti book](http://fennica-fennica.rahtiapp.fi/) shows the sections but when scrolling with mouse or keyboard, it disappears. Is it possible to keep it visible?

**Comment by ElliotvGP** [comment]
I don't have this issue ? 
The table of content on the left never moves and the one on the right also stay at the same place even after scrolling. 
The difference is that the TOC on the right is specific to the current page and only appear if the page have one or more subtitles. 

On which page did you experienced this issue ?

**Comment by antagomir** [comment]
On the landing page and all subpages where I navigate, the left TOC is collapsed as soon as I try to scroll the text body.

I am using Linux & Chromium. 

Interestingly, Firefox does not seem to suffer from this issue..

If solution can be reasonably found, it would be good to solve. Otherwise we can leave it as is.

**Comment by ElliotvGP** [comment]
Ok so I've installed Chromium and tried but I didn't have this issue. I also tried on windows on Firefox and Chrome and I've still not encountered this issue. 
But, what might know what causes this phenomenon : do you have the reader-mode enabled on the book ? 
![screen](https://github.com/fennicahub/fennica/assets/73934929/cd7707e2-5c82-44a2-9f27-78cb9f87a863)

**Comment by ElliotvGP** [comment]
(sorry I miss clicked) 
But when it's enabled, the reader mode automatically hide the TOC. 
And it's seems that on chrome, the reader mode is by default activated (Jeba had the same problem the first time he reviewed the book). 
Can you tell me if this is where the error would come from?

**Comment by antagomir** [comment]
Yes, this is it!

**Comment by ElliotvGP** [comment]
Oh that's perfect!
So we can choose to either leave the option or remove it. Personally I find this option quite confusing and ultimately not so useful (I added it because there was a similar option in the old book). I do not know what you think about it ?

**Comment by antagomir** [comment]
Could you leave the source code but comment in out, we can activate later if needs arise?
