### ISSUE TITLE
Add acknowledgments section

### ISSUE THREAD

**Issue by antagomir** [fennicahub/fennica#58]
Add acknowledgments section including information on 

- authors: Julia Matveeva, Osma Suominen, Kati Launis, Leo Lahti  
- contributors: Jeba Akewak, Pyry Kantanen, Teo & Elliot
- reference to our earlier publication on Fennica with Jani Marjanen, Mikko Tolonen
- funders (Research Council of Finland DHL-FI project; FIN-CLARIAH research infrastructure); with links to their respective websites

**Comment by antagomir** [comment]
This section can be in the end, without section number.

**Comment by ElliotvGP** [comment]
When you say to add a reference to your earlier publication on Fennica with Jani Marjanen, Mikko Tolonen, it is this one ? 
https://kansalliskirjasto.finna.fi/Record/fikka.5571642?sid=3027054824

(it's the only publication with both Jani Marjanen and Mikko Tolonen I could find on the national Finnish bibliography website)

**Comment by antagomir** [comment]
A national public sphere? Analyzing the language, location, and form of newspapers in finland, 1771–1917
Marjanen J, Vaara V, Kanner A, Roivainen H, Mäkelä E, Lahti L & Tolonen M.
Journal of European Periodical Studies 4(1), 2019
Special issue: Digital Approaches Towards Serial Publications
[10.21825/jeps.v4i1.10483](https://doi.org/10.21825/jeps.v4i1.10483) | [PDF](https://github.com/openresearchlabs/openresearchlabs.github.io/blob/master/content/publication_resources/papers/2019-Marjanen-JEPS.pdf)

Bibliographic data science and the history of the book (c. 1500–1800)
Lahti L, Marjanen J, Roivainen H & Tolonen M.
Cataloging & Classification Quarterly 57(1) Routledge, 2019
Special issue.
[10.1080/01639374.2018.1543747](https://doi.org/10.1080/01639374.2018.1543747) | [PDF](https://github.com/openresearchlabs/openresearchlabs.github.io/blob/master/content/publication_resources/papers/2019-Lahti-CCQ.pdf)

**Comment by ElliotvGP** [comment]
I added the acknowledgements in the "appendices" section

**Comment by antagomir** [comment]
Also close the issue when all is ready, or declare if there are open discussion points.
